# These are supported funding model platforms

github: brodante/KeyGuardian
patreon: null
open_collective: null
ko_fi: null
tidelift: null
community_bridge: null
custom:
  - type: upi
    url: upi://mizuhara@apl
